# Generated by Django 5.0.1 on 2024-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_alter_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
